### ISSUE TITLE
Global summer2 production V2 - Few TIR ARD data

### ISSUE THREAD

**Issue by savmickael** [WorldCereal/classification-docker#74]
For example `18MYT_108`, we get the following error:

```
2022-11-19 04:54:17.908 | ERROR    | 140593718036288:satio.utils.logs:wrapper_exitlog:96 - Error occurred while processing task with task id '18MYT_108':

Incomplete collection `TIR`: got a collection size of 1 which is less than the threshold of 2.
Traceback (most recent call last):

  File "/opt/ewoc_classif_venv/bin/ewoc_classif", line 8, in <module>
    sys.exit(run())
    │   │    └ <function run at 0x7fddeedef0d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 196, in run
    main(sys.argv[1:])
    │    │   └ ['/opt/ewoc_classif_venv/bin/ewoc_classif', '18MYT', 'c728b264-5c97-4f4c-81fe-1500d4c4dfbd_20090_20221027083824', '--end-seas...
    │    └ <module 'sys' (built-in)>
    └ <function main at 0x7fddeedef160>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 170, in main
    run_classif(
    └ <function run_classif at 0x7fddeedef1f0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 344, in run_classif
    process_blocks(
    └ <function process_blocks at 0x7fde86499ee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 98, in process_blocks
    ret = run_tile(
          └ <function run_tile at 0x7fddeedefee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 479, in run_tile
    result = _log_run_block(tup)
             │              └ ('18MYT_108', Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon.P...
             └ <function run_tile.<locals>._log_run_block at 0x7fddedae5dc0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 240, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('18MYT_108', Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7fddedae5ee0>
> File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 75, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('18MYT_108', Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7fddedae5e50>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 459, in _log_run_block
    _run_block(outputfolder, processing_tuple)
    │          │             └ ('18MYT_108', Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon.P...
    │          └ PosixPath('/tmp/18MYT_52c4ef')
    └ <function _run_block at 0x7fddeedef9d0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 310, in _run_block
    chain.process(block.tile, block.bounds,
    │     │       │     │     │     └ <_collections._tuplegetter object at 0x7fdde95affa0>
    │     │       │     │     └ Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon.Polygon object ...
    │     │       │     └ <_collections._tuplegetter object at 0x7fdde9696ca0>
    │     │       └ Pandas(Index=108, tile='18MYT', bounds=(792120, 9197640, 802360, 9207880), geometry=<shapely.geometry.polygon.Polygon object ...
    │     └ <function CropTypeProcessor.process at 0x7fddeecb0940>
    └ <worldcereal.processors.CropTypeProcessor object at 0x7fdde508bb80>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/processors.py", line 2313, in process
    irrfeatures = self.get_features(
                  │    └ <function ClassificationProcessor.get_features at 0x7fddeeaf7430>
                  └ <worldcereal.processors.CropTypeProcessor object at 0x7fdde508bb80>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/processors.py", line 1680, in get_features
    data_collections = self._filtered_collections(collections,
                       │    │                     └ {'OPTICAL': <worldcereal.collections.WorldCerealOpticalTiledCollection object at 0x7fdded91f460>, 'METEO': <worldcereal.colle...
                       │    └ <function ClassificationProcessor._filtered_collections at 0x7fddeeaf7ca0>
                       └ <worldcereal.processors.CropTypeProcessor object at 0x7fdde508bb80>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/processors.py", line 1643, in _filtered_collections
    _ = check_collection(coll, collid,
        │                │     └ 'TIR'
        │                └ <worldcereal.collections.WorldCerealThermalTiledCollection object at 0x7fdde7976070>
        └ <function check_collection at 0x7fddeef1a430>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/utils/io.py", line 133, in check_collection
    raise_coll_size_failure(collsize, min_size, name)
    │                       │         │         └ 'TIR'
    │                       │         └ 2
    │                       └ 1
    └ <function raise_coll_size_failure at 0x7fddeef1a3a0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/utils/io.py", line 94, in raise_coll_size_failure
    raise CollectionError(msg)
          │               └ 'Incomplete collection `TIR`: got a collection size of 1 which is less than the threshold of 2.'
```

**Comment by savmickael** [comment]
18MYT tile:
- overview in South America
![18MYT_108_overview](https://user-images.githubusercontent.com/3954788/202855319-bca2e861-cd61-4ed6-b1a8-1c7e61c2882a.png)
- local gsat view
![18MYT_108_local_gsat](https://user-images.githubusercontent.com/3954788/202855316-01e92abb-63aa-4e37-8ce1-160d356f1aec.png)

Available ARD TIR in the ARD bucket:
-20201011
-20201011
-20201018	
-20201119	
-20201221
-20201230
-20210122
-20210207
-20210223
-20210311
-20210320
-20210327
-20210412
-20210421
-20210507
-20210523
-20210530
-20210608
-20210615
-20210624
-20210701
-20210710
-20210717
-20210726
-20210802
-20210811
-20210818
-20210827
-20210903
-20210912
-20210919
-20210928
