### ISSUE TITLE
Global winter production V2 - IndexError

### ISSUE THREAD

**Issue by romain-bdc** [WorldCereal/classification-docker#77]
For example `58KHG_120` we get the following error :  

```
2022-11-20 14:16:23.084 | ERROR    | 140413112698688:satio.utils.logs:wrapper_exitlog:96 - Error occurred while processing task with task id '58KHG_120':

single positional indexer is out-of-bounds
Traceback (most recent call last):

  File "/opt/ewoc_classif_venv/bin/ewoc_classif", line 8, in <module>
    sys.exit(run())
    │   │    └ <function run at 0x7fb3e1c62310>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 196, in run
    main(sys.argv[1:])
    │    │   └ ['/opt/ewoc_classif_venv/bin/ewoc_classif', '58KHG', 'c728b264-5c97-4f4c-81fe-1500d4c4dfbd_10033_20220926141527', '--end-seas...
    │    └ <module 'sys' (built-in)>
    └ <function main at 0x7fb3e1c623a0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 170, in main
    run_classif(
    └ <function run_classif at 0x7fb3e1c62430>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 344, in run_classif
    process_blocks(
    └ <function process_blocks at 0x7fb4795edee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 98, in process_blocks
    ret = run_tile(
          └ <function run_tile at 0x7fb3e1c62ca0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 479, in run_tile
    result = _log_run_block(tup)
             │              └ ('58KHG_120', Pandas(Index=120, tile='58KHG', bounds=(902380, 8090200, 909780, 8097600), geometry=<shapely.geometry.polygon.P...
             └ <function run_tile.<locals>._log_run_block at 0x7fb3e0abcca0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 240, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('58KHG_120', Pandas(Index=120, tile='58KHG', bounds=(902380, 8090200, 909780, 8097600), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7fb3e0abcdc0>
> File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 75, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('58KHG_120', Pandas(Index=120, tile='58KHG', bounds=(902380, 8090200, 909780, 8097600), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7fb3e0abcd30>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 459, in _log_run_block
    _run_block(outputfolder, processing_tuple)
    │          │             └ ('58KHG_120', Pandas(Index=120, tile='58KHG', bounds=(902380, 8090200, 909780, 8097600), geometry=<shapely.geometry.polygon.P...
    │          └ PosixPath('/tmp/58KHG_ca695a')
    └ <function _run_block at 0x7fb3e1c62d30>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 247, in _run_block
    collections, fps = get_worldcereal_collections(parameters['inputs'],
                       │                           └ {'year': 2021, 'season': 'winter', 'featuresettings': {'settings': {'OPTICAL': {'bands': ['B02', 'B03', 'B04', 'B05', 'B06', ...
                       └ <function get_worldcereal_collections at 0x7fb41783b430>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 170, in get_worldcereal_collections
    if needs_s3_loader(coll):
       │               └ <worldcereal.collections.WorldCerealThermalTiledCollection object at 0x7fb3d99ba9a0>
       └ <function needs_s3_loader at 0x7fb41e414310>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/utils/__init__.py", line 306, in needs_s3_loader
    if (coll.df.path.iloc[0].startswith('s3') or
        │    └ Empty DataFrame
        │      Columns: [level, product_id, date, tile, path]
        │      Index: []
        └ <worldcereal.collections.WorldCerealThermalTiledCollection object at 0x7fb3d99ba9a0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           │    │             │                    └ 0
           │    │             └ 0
           │    └ <function _iLocIndexer._getitem_axis at 0x7fb43d853550>
           └ <pandas.core.indexing._iLocIndexer object at 0x7fb3dcabd040>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1523, in _getitem_axis
    self._validate_integer(key, axis)
    │    │                 │    └ 0
    │    │                 └ 0
    │    └ <function _iLocIndexer._validate_integer at 0x7fb43d8533a0>
    └ <pandas.core.indexing._iLocIndexer object at 0x7fb3dcabd040>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1455, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")

IndexError: single positional indexer is out-of-bounds
```
58KHG tile : 

- Overview on Vanuatu
 
![image](https://user-images.githubusercontent.com/78345373/203551932-9781e688-eef1-4c70-b6c1-722b8f17192c.png)

- Local satellite view 

![image](https://user-images.githubusercontent.com/78345373/203552608-9365a947-5764-4977-9c5a-8b0f210c5955.png)

**Comment by romain-bdc** [comment]
Above the list of tiles concerned by this issue : `26PQB`, `26QRD`, `26QPD`, `26SLH`, `26SMH`, `26SPF`,, `27QTU`, `58KHG_120`, `58LGJ`, `58KGG`, `58LGK`, `58KEB`, `58KEA`, `58KDC`, `58KGA`, `59KLV`, `59KKV`, `60KWE`, `60_KXF`, `60KXE`

**Comment by kvantricht** [comment]
Not a very transparent error, but it looks like the `WorldCerealThermalTiledCollection` has an empty dataframe. Missing TIR for these tiles?
