### ISSUE TITLE
Global cropmap and winter production V2 - The specified key does not exist

### ISSUE THREAD

**Issue by romain-bdc** [WorldCereal/classification-docker#78]
For example 24KWF_119 we get the following error : 

During first exception an other one occurred

```
2022-11-20 13:32:37.421 | ERROR    | 140653571274560:worldcereal.processors:process:2155 - Failed loading required cropland mask!
2022-11-20 13:32:37.424 | ERROR    | 140653571274560:satio.utils.logs:wrapper_exitlog:96 - Error occurred while processing task with task id '24KWF_119':

The specified key does not exist.
Traceback (most recent call last):

  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/processors.py", line 2141, in process
    maskdata = croplandcoll.load()
               │            └ <function WorldCerealProductCollection.load at 0x7febde906700>
               └ <worldcereal.collections.WorldCerealProductCollection object at 0x7febdceb7ee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/collections.py", line 978, in load
    arr = self._loader._load_array_bounds(filename, bounds)
          │    │       │                  │         └ (592140, 7990240, 602380, 7997640)
          │    │       │                  └ 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_20087_20221027083611/24KWF/2021_annual/2021_annual_20087_annualcropland_c...
          │    │       └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d0d0>
          │    └ <worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febd92acfd0>
          └ <worldcereal.collections.WorldCerealProductCollection object at 0x7febd92acf70>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           │      │       │        │        └ {}
           │      │       │        └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febd92acfd0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           │      │       └ ()
           │      └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>
           └ <function retry.<locals>.retry_decorator at 0x7fec1ab7bf70>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/retry.py", line 84, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           │                │       │   │       │        │           │      │      │          │        └ 0
           │                │       │   │       │        │           │      │      │          └ 1
           │                │       │   │       │        │           │      │      └ None
           │                │       │   │       │        │           │      └ 5
           │                │       │   │       │        │           └ 20
           │                │       │   │       │        └ <class 'Exception'>
           │                │       │   │       └ {}
           │                │       │   └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febd92acfd0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           │                │       └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>
           │                └ <class 'functools.partial'>
           └ <function __retry_internal at 0x7fec1ac23700>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/retry.py", line 45, in __retry_internal
    return f()
           └ functools.partial(<function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>, <worldcereal.geoloader.EWOCS3ParallelLoad...
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 749, in new_function
    return timeout_wrapper(*args, **kwargs)
           │                │       └ {}
           │                └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febd92acfd0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           └ <satio.utils._Timeout object at 0x7febdceb7250>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 806, in __call__
    return self.value
           │    └ <property object at 0x7fec1ad788b0>
           └ <satio.utils._Timeout object at 0x7febdceb7250>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 829, in value
    raise load
          └ RasterioIOError('The specified key does not exist.')

rasterio.errors.RasterioIOError: The specified key does not exist.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/ewoc_classif_venv/bin/ewoc_classif", line 8, in <module>
    sys.exit(run())
    │   │    └ <function run at 0x7febde66f940>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 196, in run
    main(sys.argv[1:])
    │    │   └ ['/opt/ewoc_classif_venv/bin/ewoc_classif', '24KWF', 'c728b264-5c97-4f4c-81fe-1500d4c4dfbd_20087_20221027083611', '--end-seas...
    │    └ <module 'sys' (built-in)>
    └ <function main at 0x7febde66ff70>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/cli.py", line 170, in main
    run_classif(
    └ <function run_classif at 0x7febde66fa60>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 344, in run_classif
    process_blocks(
    └ <function process_blocks at 0x7fec75d18ee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/ewoc_classif/classif.py", line 98, in process_blocks
    ret = run_tile(
          └ <function run_tile at 0x7febde718670>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 479, in run_tile
    result = _log_run_block(tup)
             │              └ ('24KWF_119', Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon.P...
             └ <function run_tile.<locals>._log_run_block at 0x7febdd226c10>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 240, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('24KWF_119', Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7febdd226d30>
> File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/logs.py", line 75, in wrapper_exitlog
    value = func(*args, **kwargs)
            │     │       └ {}
            │     └ (('24KWF_119', Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon....
            └ <function run_tile.<locals>._log_run_block at 0x7febdd226ca0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 459, in _log_run_block
    _run_block(outputfolder, processing_tuple)
    │          │             └ ('24KWF_119', Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon.P...
    │          └ PosixPath('/tmp/24KWF_a3127e')
    └ <function _run_block at 0x7febde718040>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/worldcereal_products.py", line 310, in _run_block
    chain.process(block.tile, block.bounds,
    │     │       │     │     │     └ <_collections._tuplegetter object at 0x7febdd194ac0>
    │     │       │     │     └ Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon.Polygon object ...
    │     │       │     └ <_collections._tuplegetter object at 0x7febdd194820>
    │     │       └ Pandas(Index=119, tile='24KWF', bounds=(592140, 7990240, 602380, 7997640), geometry=<shapely.geometry.polygon.Polygon object ...
    │     └ <function CropTypeProcessor.process at 0x7febde7189d0>
    └ <worldcereal.processors.CropTypeProcessor object at 0x7febd92acf10>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/processors.py", line 2151, in process
    maskdata = croplandcoll.load()
               │            └ <function WorldCerealProductCollection.load at 0x7febde906700>
               └ <worldcereal.collections.WorldCerealProductCollection object at 0x7febdceb7ee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/worldcereal/collections.py", line 978, in load
    arr = self._loader._load_array_bounds(filename, bounds)
          │    │       │                  │         └ (592140, 7990240, 602380, 7997640)
          │    │       │                  └ 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_20087_20221027083611/24KWF/2020_annual/2020_annual_20087_annualcropland_c...
          │    │       └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d0d0>
          │    └ <worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febdce9c9d0>
          └ <worldcereal.collections.WorldCerealProductCollection object at 0x7febdceb7ee0>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           │      │       │        │        └ {}
           │      │       │        └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febdce9c9d0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           │      │       └ ()
           │      └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>
           └ <function retry.<locals>.retry_decorator at 0x7fec1ab7bf70>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/retry.py", line 84, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           │                │       │   │       │        │           │      │      │          │        └ 0
           │                │       │   │       │        │           │      │      │          └ 1
           │                │       │   │       │        │           │      │      └ None
           │                │       │   │       │        │           │      └ 5
           │                │       │   │       │        │           └ 20
           │                │       │   │       │        └ <class 'Exception'>
           │                │       │   │       └ {}
           │                │       │   └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febdce9c9d0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           │                │       └ <function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>
           │                └ <class 'functools.partial'>
           └ <function __retry_internal at 0x7fec1ac23700>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/retry.py", line 45, in __retry_internal
    return f()
           └ functools.partial(<function S3ParallelLoader._load_array_bounds at 0x7fec1ab7d1f0>, <worldcereal.geoloader.EWOCS3ParallelLoad...
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 749, in new_function
    return timeout_wrapper(*args, **kwargs)
           │                │       └ {}
           │                └ (<worldcereal.geoloader.EWOCS3ParallelLoader object at 0x7febdce9c9d0>, 's3://ewoc-prd/c728b264-5c97-4f4c-81fe-1500d4c4dfbd_2...
           └ <satio.utils._Timeout object at 0x7febd4902760>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 806, in __call__
    return self.value
           │    └ <property object at 0x7fec1ad788b0>
           └ <satio.utils._Timeout object at 0x7febd4902760>
  File "/opt/ewoc_classif_venv/lib/python3.8/site-packages/satio/utils/__init__.py", line 829, in value
    raise load
          └ RasterioIOError('The specified key does not exist.')

rasterio.errors.RasterioIOError: The specified key does not exist.
```

24KWF tile :

- Overview on coast of Brasil

![image](https://user-images.githubusercontent.com/78345373/203557128-d3758f4e-0d9b-479a-b01a-e071ce4cb532.png)

- Local satellite view

![image](https://user-images.githubusercontent.com/78345373/203566569-12838d06-5259-415c-a421-50ac83017c64.png)

**Comment by kvantricht** [comment]
Error happens here: `maskdata = croplandcoll.load()` which is where the cropland mask is supposed to be loaded. I think the issue is that the cropland was not generated for this tile, probably a tile in error?
